#!/bin/sh
if [ "X$1" != "X" ]
then
    git checkout "$1" || git checkout -b "$1" 
fi
current_branch=`git rev-parse --abbrev-ref HEAD`
git stash
git checkout master
git pull
git checkout ${current_branch}
git rebase master
git pull origin ${current_branch}
git stash apply