#!/bin/sh
if [ "X$1" != "X" ]
then
    git checkout "$1" || git checkout -b "$1" 
fi
current_branch=`git rev-parse --abbrev-ref HEAD`
git stash
git checkout master
git pull main master
git push origin master
git checkout ${current_branch}
git pull origin ${current_branch}
git merge master
git stash apply